spring:
  application:
    name: spring-boot-server
  datasource:
    url: jdbc:mysql://localhost:3306/cs590
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    sql:
      init:
        mode: always
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8080